In [1]:
filename = './API/kakaoAPI.txt'
with open(filename) as f:
    api_key = f.read()

In [2]:
import requests
from urllib.parse import quote
import json

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import folium
# from shapely.geometry import Polygon
%matplotlib inline
import matplotlib.font_manager
import re

# # 폰트 설정
# mpl.rc('font', family='NanumGothic')
# # 유니코드에서  음수 부호설정
# mpl.rc('axes', unicode_minus=False)

In [4]:
from matplotlib.colors import Normalize
import matplotlib.pyplot as plt
plt.rc('font',family='Malgun Gothic')

In [13]:
# 송파구 cctv
df = pd.read_csv('./시각화 데이터/datos_전처리완료/송파구_cctv.csv', encoding='utf-8')
df.head()

   자치구                       안심 주소       위도        경도
0  송파구         1040393-2 거여동 550-2  37.4921  127.1484
1  송파구  1030303-2 거여동 136-106호 맞은편  37.4962  127.1448
2  송파구          1040453-2 거여동 31-9  37.4926  127.1460
3  송파구            1040453 거여동 31-9  37.4925  127.1460
4  송파구         1050054 마천1동 211-90  37.4942  127.1550

In [14]:
# 어린이 보행자 사고다발지역 
df2 = pd.read_csv('./시각화 데이터/datos_전처리완료/어린이 보행자 사고다발지역.csv', encoding='utf-8')
df2.head()

,시도,시군구,지점명,발생건수,사상자수,사망자수,중상자수,경상자수,부상신고자수,경도,위도
0,서울특별시,용산구,서울특별시 용산구 한남동(순천향병원 부근),3,3,0,0,2,1,127.005586,37.533295
1,서울특별시,성동구,서울특별시 성동구 행당동(무학여고앞 부근),4,5,0,0,5,0,127.032724,37.558635
2,서울특별시,광진구,서울특별시 광진구 구의동(슬기유치원앞 부근),3,3,0,2,1,0,127.093095,37.552232
3,서울특별시,광진구,서울특별시 광진구 광장동(광장사거리 부근),5,5,0,1,3,1,127.103648,37.544331
4,서울특별시,중랑구,서울특별시 중랑구 중화동(태능시장 부근),3,3,0,0,2,1,127.076933,37.598100

In [31]:
songpa = df2[df2['시군구'] == '송파구']
songpa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 27 to 149
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시도      13 non-null     object
 1   시군구     13 non-null     object
 2   지점명     13 non-null     object
 3   발생건수    13 non-null     int64
 4   사상자수    13 non-null     int64
 5   사망자수    13 non-null     int64
 6   중상자수    13 non-null     int64
 7   경상자수    13 non-null     int64
 8   부상신고자수  13 non-null     int64
 9   경도      13 non-null     float64
 10  위도      13 non-null     float64
dtypes: float64(2), int64(6), object(3)
memory usage: 1.2+ KB

In [ ]:
# 송파구 학교위치에 맞는 cctv 와 보행자 지도에 나타내기

lat_df_ele = df['위도']
lng_df_ele = df['경도']
lat_df_cc = songpa_df2['위도']
lng_df_cc = songpa_df2['경도']

# 지도의 중심을 위도(latitude)와 경도(longitude)의 평균값으로 설정합니다.
center_latitude = (lat_df_ele.mean() + lat_df_cc.mean()) / 2
center_longitude = (lng_df_ele.mean() + lng_df_cc.mean()) / 2

# folium의 Map을 생성합니다.
map = folium.Map(location=[center_latitude, center_longitude], zoom_start=12)

# 첫 번째 데이터프레임에서 Marker를 생성하고, 색깔을 지정해줍니다.
for lat, lon in zip(lat_df_ele, lng_df_ele):
    folium.Marker(location=[lat, lon], icon=folium.Icon(color='red')).add_to(map)

# 두 번째 데이터프레임에서 Marker를 생성하고, 색깔을 지정해줍니다.
for lat, lon in zip(lat_df_cc, lng_df_cc):
    folium.Marker(location=[lat, lon], icon=folium.Icon(color='blue')).add_to(map)

# 지도를 출력합니다.
map